# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160909_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Добавить комментарии'),
        ),
    ]
