# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160911_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.date(2016, 9, 12)),
            preserve_default=False,
        ),
    ]
