# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160912_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
